### ISSUE TITLE
Uncaught exception when deleting host with existing tunnels

### ISSUE THREAD

**Issue by invliD** [invliD/lana-dashboard#31]
```
Traceback (most recent call last):
  File "…/virtualenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "…/virtualenv/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "…/virtualenv/lib/python3.4/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "…/virtualenv/lib/python3.4/site-packages/django/views/decorators/http.py", line 42, in inner
    return func(request, *args, **kwargs)
  File "./lana_dashboard/lana_data/views/hosts.py", line 19, in delete_host
    host.delete()
  File "…/virtualenv/lib/python3.4/site-packages/django/db/models/base.py", line 870, in delete
    return collector.delete()
  File "…/virtualenv/lib/python3.4/site-packages/django/db/models/deletion.py", line 316, in delete
    sender=model, instance=obj, using=self.using
  File "…/virtualenv/lib/python3.4/site-packages/django/db/transaction.py", line 223, in __exit__
    connection.commit()
  File "…/virtualenv/lib/python3.4/site-packages/django/db/backends/base/base.py", line 242, in commit
    self._commit()
  File "…/virtualenv/lib/python3.4/site-packages/django/db/backends/base/base.py", line 211, in _commit
    return self.connection.commit()
  File "…/virtualenv/lib/python3.4/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "…/virtualenv/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "…/virtualenv/lib/python3.4/site-packages/django/db/backends/base/base.py", line 211, in _commit
    return self.connection.commit()
django.db.utils.IntegrityError: update or delete on table "lana_data_host" violates foreign key constraint "lana_data_tunnelendpoint_host_id_5858d000_fk_lana_data_host_id" on table "lana_data_tunnelendpoint"
DETAIL:  Key (id)=(#) is still referenced from table "lana_data_tunnelendpoint".
```

**Comment by invliD** [comment]
Fixed in d237230.
